MoneServer/Controllers/PlacesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Net.Http.Headers;
using MoneServer.Data;
using MoneServer.Data.Entities;
using MoneServer.Domain;
using MoneServer.Repositories;
using MoneServer.Services;
using MoneServer.ViewModels;

namespace MoneServer.Controllers
{
    public class PlacesController : Controller
    {
        //private readonly ApplicationDbContext _context;
        private readonly IPlaceServise _placeServise;
        private readonly IGalleryServise _galleryServise;
        private readonly IFeedbackServise _feedbackServise;
        private readonly IHostingEnvironment _environment;
        private readonly FileUploadService _fileUploadService;
        private readonly UserManager<AppliactionUser> _userManager;

        public PlacesController(
            IGalleryServise galleryServise,
            IPlaceServise placeServise,
            IFeedbackServise feedbackServise,
            UserManager<AppliactionUser> userManager,
            IHostingEnvironment environment,
            FileUploadService fileUploadService)
        {
            _galleryServise = galleryServise;
            _placeServise = placeServise;
            _feedbackServise = feedbackServise;

            _environment = environment;
            _fileUploadService = fileUploadService;

            _userManager = userManager;
        }

        // GET: Places
        public IActionResult Index(int page =1)
        {
            int pageSize = 3;
            int coun =  _placeServise.GetList().ToList().Count();
            IEnumerable<Place> places =  _placeServise.GetList().ToList();

            PageViewModel pageViewModel = new PageViewModel(coun, page, pageSize);
            PlacesVM vm = new PlacesVM
            {
                Places = places.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                PageViewModel = pageViewModel

            };



            return View(vm);
        }

        // GET: Places/Details/5
        public async Task<IActionResult> Details(string id)
        {
            IEnumerable<Gallery> galleries = null;
            IEnumerable<Feedback> feedbacks = null;
            if (id == null)
            {
                return NotFound();
            }

            Place place = null;
            try
            {
                place = await _placeServise.Find(id);
                galleries = _galleryServise.GetList().Where(x => x.ParentId == id);
                feedbacks = _feedbackServise.GetList().Where(x => x.PlaceId == id);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }


            if (place == null)
            {
                return NotFound();
            }

            PlaceDetailsVM model = new PlaceDetailsVM
            {
                Id = id,
                Name = place.Name,
                ImagePath = place.ImagePath,
                Feedbacks = feedbacks,
                Galleries = galleries,
                Description = place.Description,
                CreateAt = place.CreateAt,
                Rating = place.Rating
            };



            return View(model);
        }

        // GET: Places/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Places/Create
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePlaceVM input)
        {
            if (ModelState.IsValid)
            {
                var pathAvatar = Path.Combine(_environment.WebRootPath,
                    $"images\\Place\\{_userManager.GetUserId(User)}");
                _fileUploadService.Upload(pathAvatar, input.PlaceAvatar.FileName, input.PlaceAvatar);
                String avatarPath = $"images/Place/{_userManager.GetUserId(User)}/{input.PlaceAvatar.FileName}";


                AppliactionUser user = await _userManager.GetUserAsync(User);
                var place = new Place
                {
                    Name = input.Name,
                    Description = input.Description,
                    ImagePath = avatarPath,
                    CreateAt = DateTime.Now,
                    Rating = 0,
                    User = user,
                    UserId = user.Id
                };

                Place created = await _placeServise.Create(place);
                if (created != null)
                {
                    foreach (IFormFile file in input.PlaceGallery)
                    {
                        var path = Path.Combine(_environment.WebRootPath, $"images\\Gallery\\{user.Id}");
                        _fileUploadService.Upload(path, file.FileName, file);
                        String imagePath = $"images/Gallery/{user.Id}/{file.FileName}";


                        Gallery gallery = new Gallery
                        {
                            Parent = created,
                            ParentId = created.Id,
                            ImagePath = imagePath
                        };

                        await _galleryServise.Create(gallery);
                    }

                    return RedirectToAction(nameof(Index));
                }
            }

            return View(input);
        }

        // GET: Places/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Place place = null;
            try
            {
                place = await _placeServise.Find(id);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return NotFound();
            }

            if (place == null)
            {
                return NotFound();
            }

            return View(place);
        }

        // POST: Places/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name,Description,UserId,CreateAt,ImagePath,Rating,Id")]
            Place place)
        {
            if (id != place.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _placeServise.Update(place);
                }
                catch (DbUpdateConcurrencyException)
                {
                    bool x = await PlaceExists(place.Id);
                    if (!x)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }


            return View(place);
        }

        // GET: Places/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Place place = null;
            try
            {
                place = await _placeServise.Find(id);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return NotFound();
            }

            if (place == null)
            {
                return NotFound();
            }

            return View(place);
        }

        // POST: Places/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            Place place = null;
            try
            {
                place = await _placeServise.Find(id);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return NotFound();
            }


            _placeServise.Delete(place);
            return RedirectToAction(nameof(Index));
        }

        private async Task<bool> PlaceExists(string id)
        {
            Place place = null;
            try
            {
                place = await _placeServise.Find(id);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                return false;
            }

            return place != null;
        }


        public IActionResult SearchResult(String key)
        {
            ViewBag.count = 0;
            int pageSize = 3;

            var places =  _placeServise.GetList()
                .Where(x => x.Name.Contains(key) || x.Description.Contains(key)).ToList();

            ViewBag.count = places.Count();
     
            return PartialView("Searchresult",places);

        }

        public async Task<IActionResult> FeedbackResult(String feedback, String placeId)
        {
            if (feedback == null)
            {
                var feedbacks = _feedbackServise.GetList().Where(x => x.PlaceId == placeId).ToList();
                ;
                return PartialView("FeedbackResult", SortDate(feedbacks));
            }
            if (!feedback.Equals(""))
            {
                Place place = null;
                AppliactionUser user = await _userManager.GetUserAsync(User);

                try
                {
                    place = await _placeServise.Find(placeId);
                }
                catch (Exception e)
                {
                    Console.WriteLine(e);
                    return NotFound();
                }


                Feedback fb = new Feedback

MoneServer/Views/Shared/FeedbackResult.cshtml
@model IEnumerable<Feedback>
@using MoneServer.Data.Entities

<div class="row">

    @foreach (var item in Model)
    {

        <br />
        <div class="col-sm-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-body">
                    <img class="figure-img" src="https://localhost:5001/@item.User.ImagePath" height="40" width="40"/>
                    <h5 class="card-title">User: @item.User.UserName</h5>
                    <h5 class="card-title">Text: @item.Text</h5>
                    <p class="card-text">Date: @item.CreateAt</p>

                </div>
            </div>
        </div>
        <br />
    }

</div>

MoneServer/Views/Shared/Searchresult.cshtml
@model IEnumerable<Place>
@using Microsoft.AspNetCore.Identity
@using MoneServer.Data.Entities

@{
    ViewData["Title"] = "Searchresult";
}

<h1 class="text-center">Searchresult @Model.Count() </h1>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-sm-12 col-md-6 col-lg-4">


            <div class="card" style="width: 18rem;">
                <a asp-action="Details" asp-controller="Places" asp-route-id="@item.Id">
                    <img class="card-img-top" src="@item.ImagePath" width="100" height="200" alt="Card image cap">
                </a>
                <div class="card-body">
                    <h5 class="card-title">@item.Name</h5>
                    <p class="card-text">@item.Description</p>
                    <a asp-action="Details" asp-controller="Places" asp-route-id="@item.Id" class="btn btn-primary">Open</a>
                </div>
            </div>


        </div>
    }

</div>

MoneServer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MoneServer</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Places" asp-action="Index">Mone</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>
                <ul class="navbar-nav flex-grow-1">
                  
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Search</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Places" asp-action="Index">Places</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
               
            </div>
           
        </div>
      
    </nav>
   
</header>
<div class="container">
    <partial name="_CookieConsentPartial"/>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2019 - MoneServer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
    </script>
</environment>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)
</body>
</html>